on:
  push:
     branches:
       - master

name: copy stuff
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: push
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '/' # Folder to copy
        destination_repo: 'some-du6e/games-site' # Target repo
        destination_folder: '/'
        user_email: 'a@a.com'
        user_name: 'awesomebot'
        commit_message: "AUTO: copy stuff"
        git_server: 'github.com'
